pph-collective/TITAN

.github/workflows/deploy_docs.yml
.github/workflows/main.yml
mkdocs.yml

Deploys docs to github pages on push to main,

add workflow file for doc deployment

---

tests/agent_test.py
tests/features/haart_test.py
tests/features/high_risk_test.py
tests/features/incar_test.py
tests/features/prep_test.py
tests/model_test.py
tests/output_test.py
tests/population_test.py
titan/agent.py
titan/features/base_feature.py
titan/features/haart.py
titan/features/high_risk.py
titan/features/incar.py
titan/features/prep.py
titan/features/random_trial.py
titan/features/vaccine.py
titan/model.py
titan/output.py
titan/population.py

* `time` means the time step a thing happened
* `duration` means the time remaining until a thing happens

feat: standardize time usage

---

tests/features/high_risk_test.py
tests/features/incar_test.py
tests/output_test.py
titan/features/high_risk.py
titan/features/incar.py
titan/model.py
titan/population.py

* make incar high_risk agnostic, put all logic in high risk
* the checks are for if the incar event happened the last time period as that way each agent is guaranteed to be considered once - thoughts?

Split high risk from incar

---

docs/index.md

docs: add iframe and caption to docs

---

mkdocs.yml

Material update the feature names

Docs update

---

mkdocs.yml
tests/model_test.py
tests/output_test.py
tests/params/basic.yml
tests/utils_test.py
titan/agent.py
titan/exposures/knowledge.py
titan/features/haart.py
titan/features/random_trial.py
titan/location.py
titan/model.py
titan/output.py
titan/params/outputs.yml
titan/partnering.py
titan/population.py
titan/population_io.py
titan/run_titan.py
titan/utils.py

* create bin functions, use them
* Make location's init_weights feel less copy/pasted
* Break down haart update into methods, use initiate for init too
* Make components reportable

Odds and Ends

---

tests/integration_test.py
tests/location_test.py
titan/agent.py
titan/features/incar.py
titan/location.py
titan/parse_params.py
titan/population.py
titan/settings/mississippi/model.yml
titan/settings/scott/demographics.yml

* Add checks to make sure only `pop_num` agents are created
* Fix incar integration test
* Fix Scott `sex_role` probs
* Remove duplicate `drug_type` class in mississippi

fix: check populations to make sure 1 ppl is ceated, fix incar test

---

tests/partnering_test.py
titan/params/assort_mix.yml
titan/partnering.py

closes #166 closes #167 closes #168

feat: flex assorting - nested keys, same, cross-attribute

---

tests/partnering_test.py
titan/params/assort_mix.yml
titan/partnering.py

feat: assort rules by bond_type

---

.github/workflows/unit-tests.yml
tests/population_io_test.py

Unit test: don't check component equality

---

pyproject.toml
tests/integration_test.py
tests/model_test.py
tests/params/basic.yml
tests/params/simple_integration.yml
titan/exposures/hiv.py
titan/model.py
titan/params/hiv.yml
titan/params/partnership.yml
titan/probabilities.py

Finish out the tests in #13 
Need to bump patch version due to params default fix for haart/injection

Integration tests

---

missouri/demographics.yml
missouri/model.yml

Missouri setting

---

titan/params/assort_mix.yml
titan/params/demographics.yml
titan/params/outputs.yml

I don't think this warrants a version bump, do you?

docs: clean up use of ' in descriptions, use more `

---

titan/params/assort_mix.yml
titan/params/demographics.yml
titan/params/outputs.yml

docs md updates

---

titan/settings/rhode-island/demographics.yml
titan/settings/rhode-island/model.yml

Rhode island setting

---

pyproject.toml
titan/model.py
titan/settings/mississippi/model.yml

Remove unused timeline scaling, fix bug in timeline scaling

Ms correction

---

titan/settings/missouri/demographics.yml

missouri edits

---

pyproject.toml
titan/settings/nyc-msm/demographics.yml
titan/settings/nyc-msm/location.yml
titan/settings/nyc-msm/model.yml

Corrects the NYC setting using calibrated params

Nyc updates

---

tests/model_test.py

Fixed bug causing a test to occasionally fail

test: update die_and_replace to enter_and_exit

---

titan/distributions.py
titan/features/high_risk.py
titan/interactions/injection.py
titan/interactions/sex.py
titan/population.py
titan/utils.py

Updates to make poisson a distribution rather than a util.

Poisson update

---

mkdocs.yml
titan/model.py

Updating docstrings to make the docs site make sense.

docs(enter_exit): update docstrings for entrance and exit

---

tests/integration_test.py
tests/model_test.py
tests/params/basic.yml
tests/params/basic_seeded.yml
tests/params/basic_seeded_error.yml
tests/params/multi_location.yml
tests/params/simple_integration.yml
titan/model.py
titan/params/enter_exit.yml
titan/params/features.yml
titan/settings/atlanta/model.yml
titan/settings/chicago/chicago_baseCase.yml
titan/settings/mississippi/model.yml
titan/settings/missouri/model.yml
titan/settings/nyc-msm/model.yml
titan/settings/rhode-island/model.yml
titan/settings/scott/model.yml

Enter exit enter

---

titan/agent.py
titan/model.py
titan/output.py
titan/population.py
titan/settings/atlanta/assort_mix.yml
titan/settings/atlanta/calibration.yml
titan/settings/atlanta/demographics.yml
titan/settings/atlanta/model.yml
titan/settings/atlanta/outputs.yml
titan/settings/atlanta/partnership.yml

updates to run the atlanta model

Atlanta update

---

.github/workflows/deploy_pypi.yml
.github/workflows/unit-tests.yml
poetry.lock
pyproject.toml
tests/conftest.py
tests/exposures/knowledge_test.py
tests/integration_test.py
titan/exposures/base_exposure.py
titan/exposures/hiv.py
titan/exposures/knowledge.py
titan/exposures/monkeypox.py
titan/features/external_exposure.py
titan/features/high_risk.py
titan/features/incar.py
titan/features/partner_tracing.py
titan/features/prep.py
titan/features/random_trial.py
titan/features/syringe_services.py
titan/features/vaccine.py
titan/interactions/base_interaction.py
titan/interactions/injection.py
titan/interactions/pca.py
titan/interactions/sex.py
titan/location.py
titan/model.py
titan/output.py
titan/population.py
titan/utils.py

Fix dependencies

---

pyproject.toml
tests/integration_test.py
tests/model_test.py
titan/model.py
titan/params/partnership.yml
titan/population.py

Allows relationships to dissolve at a given timestep

Dissolve relationships

---

poetry.lock
pyproject.toml
titan/settings/atlanta-latino/assort_mix.yml
titan/settings/atlanta-latino/calibration.yml
titan/settings/atlanta-latino/demographics.yml
titan/settings/atlanta-latino/model.yml
titan/settings/atlanta-latino/outputs.yml
titan/settings/atlanta-latino/partnership.yml
titan/settings/atlanta-latino/prep.yml
titan/settings/atlanta-latino/timeline_scaling.yml

* feat: create new setting for atlanta with latinos
* upgrade python version in github actions

Atlanta latino (#239)

---

pyproject.toml
titan/settings/atlanta-latino/demographics.yml

- fixed erroneous haart values

fix: update haart for black and latino
